version: "3.9"
services:
  app:
    build: .
    container_name: backend-tecnico-app
    environment:
      - CONNECTION_STRING=${DEV_CONN_STRING}
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    command: mongod --quiet --logpath /dev/null 


volumes:
  data: